channels:
  - conda-forge
  - defaults
  - ioam/label/dev
  - ioos
  - scitools
  - ioam
dependencies:
  - python=2.7
  - pandas
  - numpy
  - shapely
  - param
  - holoviews=1.10.0a2
  - geoviews
  - geopandas


